In [3]:
import os
import datetime as dt
from datetime import datetime, timedelta
""" import pandas_datareader.data as web """
import pandas as pd
from pycaret.time_series import * 
import numpy as np

In [2]:
data_csv = pd.read_csv('./data/processed_data.csv')
display(data_csv)

,datetime,PM25,PM10,SO2,NO2,CO,O3,temp,pres,dewp,prec,wind_dire,wd,hour,woy,temp_diff
0,2013-03-01 00:00:00,3.0,6.0,3.0,8.0,300.0,44.0,-0.9,1025.8,-20.5,0.0,NW,9.3,0,9,NaN
1,2013-03-01 01:00:00,12.0,12.0,3.0,7.0,300.0,47.0,-1.1,1026.1,-21.3,0.0,NW,9.4,1,9,-0.2
2,2013-03-01 02:00:00,14.0,14.0,NaN,7.0,200.0,22.0,-1.7,1026.2,-23.0,0.0,NW,8.6,2,9,-0.6
3,2013-03-01 03:00:00,12.0,12.0,3.0,5.0,NaN,NaN,-2.1,1027.3,-23.3,0.0,NW,6.6,3,9,-0.4
4,2013-03-01 04:00:00,12.0,12.0,3.0,NaN,200.0,11.0,-2.4,1027.7,-22.9,0.0,NW,4.5,4,9,-0.3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
26299,2016-02-29 19:00:00,57.0,71.0,16.0,65.0,900.0,26.0,1.9,1026.6,-15.6,0.0,S,2.2,19,9,-0.3
26300,2016-02-29 20:00:00,70.0,78.0,23.0,64.0,1200.0,27.0,1.2,1026.3,-14.9,0.0,SSE,1.6,20,9,-0.7
26301,2016-02-29 21:00:00,76.0,79.0,26.0,79.0,1300.0,9.0,1.3,1026.1,-14.8,0.0,SSE,1.4,21,9,0.1
26302,2016-02-29 22:00:00,78.0,80.0,24.0,73.0,1200.0,13.0,1.1,1026.0,-14.6,0.0,ESE,1.4,22,9,-0.2
26303,2016-02-29 23:00:00,83.0,83.0,25.0,76.0,1300.0,9.0,0.4,1025.7,-13.7,0.0,ESE,1.0,23,9,-0.7